# Generated by Django 5.0.6 on 2024-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_alter_photographer_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
