# Generated by Django 5.0.6 on 2024-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('yourworks', models.CharField(max_length=200)),
            ],
        ),
    ]
