# Generated by Django 5.0.6 on 2024-07-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_cuslogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuslogin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cuslogin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cuslogin',
            name='mobile',
        ),
    ]
